### ISSUE TITLE
Ignore Links in X Terms 

### ISSUE THREAD

**Issue by smmkolesnikov** [OpenTermsArchive/pga-declarations#326]
Hi @OpenTermsArchive/core !

We currently have a weird issue with X terms, namely X Trackers Policy, X Law Enforcement Guidelines and X Copyright Claims Policy. 

In these webpages, there are links to other X policies that keep changing every day for about two weeks now, causing a lot of noise. What happens is that links to help.twitter.com are being removed with help.x.com, and vice versa (so it is going back and forth for some reason).

Our idea is that we need to have these links in our versions, but we would like to get rid of the unnecessary noise in the versions archive. 

Therefore, the question is: can we somehow set the engine to ignore this exact type of change? 

Thanks!

**Comment by clementbiron** [comment]
Hi @smmkolesnikov 

This type of noise seems to be due that the requested web page is regularly served by a server that does not return the latest version of the web page. This is quite common and probably one day all the front-end servers will be up to date and provide the same page. In the meantime, it is possible to correct this noise by adding a JavaScript filter.

Since it’s not common to add filters, I will open a pull request to make this correction to demonstrate it to you.
